version: '3.8'

services:
  breazy-app:
    build: .
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
