version: '3.8'

services:
  api-gateway:
      build: .
      container_name: breezy-api-server
      restart: unless-stopped
      ports:
        - "3009:3000"
      volumes:
        - ./data:/app/data
        - ./logs:/app/logs
        - ./config:/app/config:ro
      environment:
        - NODE_ENV=production
        - PORT=3000
        - JWT_SECRET=your-super-secret-jwt-key
        - DB_PATH=/app/data/api.db  # ou une autre config selon l'API
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
  
# default /var/lib/docker/volumes/mongo-data/_data
volumes:
  mongo-data: 
